version: "3"

services:
  web_app:
    container_name: cybersmart_assessment_web_app
    restart: unless-stopped
    depends_on:
      - database
      - document_store
    build:
      context: .
      target: production
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py wait_for_database
        python manage.py wait_for_document_store
        python manage.py migrate
        gunicorn --bind 0.0.0.0:8000 --threads 4 cybersmart_assessment.core.wsgi:application
    env_file: .env
    environment:
      TODO_DEBUG: "False"
    expose:
      - 8000
    volumes:
      - static_files:/home/user/static

  database:
    container_name: cybersmart_assessment_database
    image: postgres:16.1
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: "${TODO_DATABASE_NAME:?Database name is not set}"
      POSTGRES_USER: "${TODO_DATABASE_USER:?Database user is not set}"
      POSTGRES_PASSWORD: "${TODO_DATABASE_PASSWORD:?Database password is not set}"
    expose:
      - 5432
    volumes:
      - database_storage:/var/lib/postgresql/data

  document_store:
    container_name: cybersmart_assessment_document_store
    image: mongo:7.0.3
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${TODO_DOCUMENT_STORE_USER:?Document store user is not set}"
      MONGO_INITDB_ROOT_PASSWORD: "${TODO_DOCUMENT_STORE_PASSWORD:?Document store password is not set}"
      MONGO_INITDB_DATABASE: "${TODO_DOCUMENT_STORE_NAME:?Document store name is not set}"
    expose:
      - 27017
    volumes:
      - document_store_storage:/data/db

  proxy:
    container_name: cybersmart_assessment_proxy
    image: nginx:1.25.3
    depends_on:
      - web_app
    restart: unless-stopped
    volumes:
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/proxy_params:/etc/nginx/proxy_params
      - static_files:/app/static/
    ports:
      - 8080:8080

volumes:
  database_storage:
  document_store_storage:
  static_files:
