version: "3"

services:
  web_app:
    container_name: cybersmart_assessment_web_app
    restart: unless-stopped
    depends_on:
      - database
      - document_store
    build:
      context: .
      target: development
    command:
      - /bin/sh
      - -c
      - |
        python manage.py collectstatic --noinput
        python manage.py wait_for_database
        python manage.py wait_for_document_store
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8080
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ./manage.py:/home/user/app/manage.py
      - ./src/cybersmart_assessment:/home/user/app/cybersmart_assessment/
      - ./static:/home/user/static

  database:
    container_name: cybersmart_assessment_database
    image: postgres:16.1
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: "${TODO_DATABASE_NAME:?Database name is not set}"
      POSTGRES_USER: "${TODO_DATABASE_USER:?Database user is not set}"
      POSTGRES_PASSWORD: "${TODO_DATABASE_PASSWORD:?Database password is not set}"
    expose:
      - 5432
    volumes:
      - database_storage:/var/lib/postgresql/data

  document_store:
    container_name: cybersmart_assessment_document_store
    image: mongo:7.0.3
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${TODO_DOCUMENT_STORE_USER:?Document store user is not set}"
      MONGO_INITDB_ROOT_PASSWORD: "${TODO_DOCUMENT_STORE_PASSWORD:?Document store password is not set}"
      MONGO_INITDB_DATABASE: "${TODO_DOCUMENT_STORE_NAME:?Document store name is not set}"
    expose:
      - 27017
    volumes:
      - document_store_storage:/data/db

  cache:
    container_name: cybersmart_assessment_cache
    image: redis:7.2.3
    expose:
      - 6379
    restart: unless-stopped

  weather_worker:
    container_name: cybersmart_assessment_weather_worker
    build:
      context: .
      target: development
    command:
      - /bin/sh
      - -c
      - |
        python manage.py wait_for_database
        python manage.py wait_for_document_store
        rm -f /app/celerybeat-schedule
        celery \
          --app cybersmart_assessment.system.celery.app.app \
          worker \
          --beat \
          --schedule-filename=/home/user/app/celerybeat-schedule \
          --logfile=/dev/null \
          --task-events
    env_file: .env
    volumes:
      - ./manage.py:/home/user/app/manage.py
      - ./src/cybersmart_assessment:/home/user/app/cybersmart_assessment/
      - ./static:/home/user/static
    depends_on:
      - web_app
      - cache
      - document_store
    restart: on-failure

volumes:
  database_storage:
  document_store_storage:
